//! GitHub Copilot Cloud Agent Support
//!
//! Generates copilot-setup-steps.yml and .github/agents/speckit.agent.md
//! when the github-copilot tool is selected during init/update.

use anyhow::Result;
use std::fs;
use std::path::Path;

/// The Copilot tool id.
const COPILOT_TOOL_ID: &str = "github-copilot";

/// Marker for Speckit-managed Copilot files.
const OPENSPEC_MANAGED_MARKER: &str =
    "Generated by Speckit for GitHub Copilot coding agent support.";

/// File paths (relative to project root) for the generated files.
pub const COPILOT_CLOUD_FILES: CopilotCloudFiles = CopilotCloudFiles {
    setup_steps: ".github/workflows/copilot-setup-steps.yml",
    agent: ".github/agents/speckit.agent.md",
};

/// Copilot cloud file paths.
pub struct CopilotCloudFiles {
    pub setup_steps: &'static str,
    pub agent: &'static str,
}

/// Check if a tool list includes github-copilot.
pub fn includes_github_copilot(tool_ids: &[&str]) -> bool {
    tool_ids.contains(&COPILOT_TOOL_ID)
}

/// Generate the copilot-setup-steps.yml workflow file content.
pub fn generate_copilot_setup_steps() -> String {
    format!(
        "# {}\n\nname: \"Copilot Setup Steps\"\n\n\
         on:\n  workflow_dispatch:\n  push:\n    paths:\n      - .github/workflows/copilot-setup-steps.yml\n  \
         pull_request:\n    paths:\n      - .github/workflows/copilot-setup-steps.yml\n\n\
         jobs:\n  copilot-setup-steps:\n    runs-on: ubuntu-latest\n    timeout-minutes: 10\n    \
         permissions:\n      contents: read\n    steps:\n      - name: Checkout code\n        \
         uses: actions/checkout@v4\n      - name: Install Speckit CLI\n        \
         run: npm install -g @fission-ai/speckit\n      - name: Verify Speckit CLI\n        \
         run: speckit --version\n",
        OPENSPEC_MANAGED_MARKER
    )
}

/// Generate the .github/agents/speckit.agent.md custom agent file content.
pub fn generate_copilot_agent_file() -> String {
    format!(
        "---\nname: Speckit\n\
         description: \"Manages Speckit changes, specs, and workflows using the Speckit CLI.\"\n\
         tools:\n  - \"execute\"\n  - \"read\"\n  - \"search\"\n  - \"edit\"\n---\n\n\
         <!-- {} -->\n\n\
         # Speckit Agent\n\n\
         You are a specialized agent for managing Speckit workflows. Before using the `speckit` CLI, \
         run `speckit --version`. If it is unavailable, install it with `npm install -g @fission-ai/speckit`.\n\n\
         ## Available Commands\n\n\
         | Command | Purpose |\n|---------|--------|\n\
         | `speckit list [--json]` | List all changes and specs |\n\
         | `speckit show <item> [--json]` | View a specific change or spec |\n\
         | `speckit validate [--all] [--json]` | Validate changes and specs |\n\
         | `speckit status [--change <name>] [--json]` | Show artifact progress |\n\
         | `speckit instructions [artifact] [--change <name>] [--json]` | Get next-step instructions |\n\
         | `speckit archive <change> --json [--yes]` | Archive a completed change |\n\n\
         ## Workflow\n\n\
         1. **Find the change**: Run `speckit list --json`.\n\
         2. **Check progress**: Run `speckit status --change <name> --json`.\n\
         3. **Follow instructions**: Run `speckit instructions --change <name> --json`.\n\
         4. **Validate**: Run `speckit validate <name> --json`.\n",
        OPENSPEC_MANAGED_MARKER
    )
}

/// Check if content matches the current generated file.
fn is_current_copilot_cloud_file(rel_path: &str, content: &str) -> bool {
    let expected = if rel_path == COPILOT_CLOUD_FILES.setup_steps {
        generate_copilot_setup_steps()
    } else if rel_path == COPILOT_CLOUD_FILES.agent {
        generate_copilot_agent_file()
    } else {
        return false;
    };
    normalize_line_endings(content) == normalize_line_endings(&expected)
}

/// Check if content matches any legacy generated file.
fn is_legacy_copilot_cloud_file(rel_path: &str, content: &str) -> bool {
    // Legacy files don't have the managed marker or have slight variations
    let normalized = normalize_line_endings(content);
    if rel_path == COPILOT_CLOUD_FILES.setup_steps {
        normalized.contains("Copilot Setup Steps") && normalized.contains("speckit")
    } else if rel_path == COPILOT_CLOUD_FILES.agent {
        normalized.contains("Speckit Agent") && normalized.contains("speckit")
    } else {
        false
    }
}

/// Check if a file is managed by Speckit.
fn is_managed_copilot_cloud_file(rel_path: &str, content: &str) -> bool {
    is_current_copilot_cloud_file(rel_path, content)
        || is_legacy_copilot_cloud_file(rel_path, content)
}

/// Normalize line endings to LF.
fn normalize_line_endings(content: &str) -> String {
    content.replace("\r\n", "\n")
}

/// Reconcile a single Copilot cloud file.
fn reconcile_copilot_cloud_file(full_path: &Path, rel_path: &str) -> Result<bool> {
    let current_content = if rel_path == COPILOT_CLOUD_FILES.setup_steps {
        generate_copilot_setup_steps()
    } else if rel_path == COPILOT_CLOUD_FILES.agent {
        generate_copilot_agent_file()
    } else {
        return Ok(false);
    };

    if !full_path.exists() {
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(full_path, &current_content)?;
        return Ok(true);
    }

    let existing = fs::read_to_string(full_path)?;
    if is_current_copilot_cloud_file(rel_path, &existing) {
        return Ok(false);
    }
    if !is_legacy_copilot_cloud_file(rel_path, &existing) {
        return Ok(false);
    }

    fs::write(full_path, &current_content)?;
    Ok(true)
}

/// Reconcile Copilot cloud agent files in the project directory.
///
/// `opt_in` carries the user's explicit choice:
///
/// * `Some(true)`  -- enable Copilot cloud setup by writing the managed
///   files (or refreshing any existing managed copies).
/// * `Some(false)` -- remove managed Copilot cloud files; user-modified
///   files are never touched.
/// * `None`        -- preserve current behaviour: write when no opt-in
///   record exists yet, otherwise keep whatever is on disk.
pub fn write_copilot_cloud_files(
    project_path: &Path,
    opt_in: Option<bool>,
) -> Result<CopilotCloudResult> {
    if opt_in == Some(false) {
        let _ = remove_copilot_cloud_files(project_path)?;
        return Ok(CopilotCloudResult {
            setup_steps_written: false,
            agent_written: false,
        });
    }

    let setup_steps_path = project_path.join(COPILOT_CLOUD_FILES.setup_steps);
    let agent_path = project_path.join(COPILOT_CLOUD_FILES.agent);
    let alternate_agent_path = project_path.join(".github/agents/speckit.md");

    // Check for conflicts with alternate agent file
    if alternate_agent_path.exists() && agent_path.exists() {
        let agent_content = fs::read_to_string(&agent_path)?;
        if is_managed_copilot_cloud_file(COPILOT_CLOUD_FILES.agent, &agent_content) {
            // Remove managed file in favor of alternate
            fs::remove_file(&agent_path)?;
            return Ok(CopilotCloudResult {
                setup_steps_written: reconcile_copilot_cloud_file(
                    &setup_steps_path,
                    COPILOT_CLOUD_FILES.setup_steps,
                )?,
                agent_written: false,
            });
        }
        // Both exist and agent is user-owned: skip
        return Ok(CopilotCloudResult {
            setup_steps_written: reconcile_copilot_cloud_file(
                &setup_steps_path,
                COPILOT_CLOUD_FILES.setup_steps,
            )?,
            agent_written: false,
        });
    }

    let setup_steps_written =
        reconcile_copilot_cloud_file(&setup_steps_path, COPILOT_CLOUD_FILES.setup_steps)?;
    let agent_written = reconcile_copilot_cloud_file(&agent_path, COPILOT_CLOUD_FILES.agent)?;

    Ok(CopilotCloudResult {
        setup_steps_written,
        agent_written,
    })
}

/// Result of writing Copilot cloud files.
#[derive(Debug, Clone)]
pub struct CopilotCloudResult {
    pub setup_steps_written: bool,
    pub agent_written: bool,
}

/// Remove copilot cloud agent files from the project directory.
pub fn remove_copilot_cloud_files(project_path: &Path) -> Result<usize> {
    let mut removed = 0;
    let paths = [
        project_path.join(COPILOT_CLOUD_FILES.setup_steps),
        project_path.join(COPILOT_CLOUD_FILES.agent),
    ];

    for full_path in &paths {
        if full_path.exists() {
            let content = fs::read_to_string(full_path)?;
            let rel_path = full_path
                .strip_prefix(project_path)
                .unwrap_or(full_path)
                .to_string_lossy()
                .to_string();
            if is_managed_copilot_cloud_file(&rel_path, &content) {
                fs::remove_file(full_path)?;
                removed += 1;
            }
        }
    }

    Ok(removed)
}

/// Read the persisted opt-in for Copilot cloud-file generation.
pub fn read_copilot_cloud_opt_in(project_path: &Path) -> Option<bool> {
    let config_path = project_path.join("speckit/config.yaml");
    if !config_path.exists() {
        return None;
    }
    let content = fs::read_to_string(&config_path).ok()?;
    let config: serde_yaml::Value = serde_yaml::from_str(&content).ok()?;
    let value = config.get("githubCopilot")?.get("cloudAgent")?.as_bool()?;
    Some(value)
}

/// True when a managed Copilot cloud file already exists.
pub fn has_existing_managed_cloud_files(project_path: &Path) -> bool {
    let paths = [
        project_path.join(COPILOT_CLOUD_FILES.setup_steps),
        project_path.join(COPILOT_CLOUD_FILES.agent),
    ];

    for full_path in &paths {
        if full_path.exists()
            && let Ok(content) = fs::read_to_string(full_path) {
                let rel_path = full_path
                    .strip_prefix(project_path)
                    .unwrap_or(full_path)
                    .to_string_lossy()
                    .to_string();
                if is_managed_copilot_cloud_file(&rel_path, &content) {
                    return true;
                }
            }
    }
    false
}

/// Effective decision on whether to generate/refresh Copilot cloud files.
pub fn is_copilot_cloud_enabled(project_path: &Path) -> bool {
    match read_copilot_cloud_opt_in(project_path) {
        Some(opt_in) => opt_in,
        None => has_existing_managed_cloud_files(project_path),
    }
}

/// Persist the Copilot cloud opt-in into speckit/config.yaml.
pub fn persist_copilot_cloud_opt_in(project_path: &Path, value: bool) -> Result<()> {
    let config_path = project_path.join("speckit/config.yaml");
    if !config_path.exists() {
        return Ok(());
    }

    let content = fs::read_to_string(&config_path)?;
    let mut config: serde_yaml::Value = serde_yaml::from_str(&content)
        .unwrap_or(serde_yaml::Value::Mapping(serde_yaml::Mapping::new()));

    if let serde_yaml::Value::Mapping(ref mut map) = config {
        let copilot_key = serde_yaml::Value::String("githubCopilot".to_string());
        let cloud_key = serde_yaml::Value::String("cloudAgent".to_string());

        if !map.contains_key(&copilot_key) {
            map.insert(
                copilot_key.clone(),
                serde_yaml::Value::Mapping(serde_yaml::Mapping::new()),
            );
        }

        if let Some(serde_yaml::Value::Mapping(copilot_map)) = map.get_mut(&copilot_key) {
            copilot_map.insert(cloud_key, serde_yaml::Value::Bool(value));
        }
    }

    let serialized = serde_yaml::to_string(&config)?;
    fs::write(&config_path, serialized)?;
    Ok(())
}

/// Return the managed cloud-file paths that currently hold user-owned content.
pub fn find_unmanaged_cloud_files(project_path: &Path) -> Vec<String> {
    let mut collisions = Vec::new();
    let paths = [COPILOT_CLOUD_FILES.setup_steps, COPILOT_CLOUD_FILES.agent];

    for rel_path in &paths {
        let full_path = project_path.join(rel_path);
        if full_path.exists()
            && let Ok(content) = fs::read_to_string(&full_path)
                && !is_managed_copilot_cloud_file(rel_path, &content) {
                    collisions.push(rel_path.to_string());
                }
    }
    collisions
}

/// Return the managed cloud-file paths that currently exist.
pub fn list_managed_cloud_files(project_path: &Path) -> Vec<String> {
    let mut present = Vec::new();
    let paths = [COPILOT_CLOUD_FILES.setup_steps, COPILOT_CLOUD_FILES.agent];

    for rel_path in &paths {
        let full_path = project_path.join(rel_path);
        if full_path.exists()
            && let Ok(content) = fs::read_to_string(&full_path)
                && is_managed_copilot_cloud_file(rel_path, &content) {
                    present.push(rel_path.to_string());
                }
    }
    present
}
